In [ ]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'letterboxd:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F4459542%2F7649925%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240415%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240415T153247Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6e00af7d2256805e401093717e80b68906b8081d69daa69aa282314bc3f3295394e34fe8bea0988b78f8a4dcc71b327b34331724f6bda16e629ba3b045c82bb53186ddcaddee94f69852974322a43300d61579b36a6648e47374dfda30da8f58842795a4bfe4a402e96316b10bd516ba0dfa68f7af242701c3bbf699239cb2be2f3d98752e1d0b9a1e30c177e25e07acfccb72b4c1486e4c14ac0679e98d34c28d76725e5690f29b6c278fa09c1dcfa55e762ccc44168f26338bbfdf0ccf312c03576367cd599dfbec5e30f8258a95ee27bf8987602ed5cd8ca22a845fc7be14007bf9af2ba039c1511bb7a7e862da5d6e326db9bf4369a0725290ff08c3598f'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')


[==================================================] 22858253891 bytes downloaded
Downloaded and uncompressed: letterboxd
Data source import complete.


In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

串流輸出內容已截斷至最後 5000 行。
/kaggle/input/letterboxd/posters/1201113.jpg
/kaggle/input/letterboxd/posters/1616178.jpg
/kaggle/input/letterboxd/posters/1725195.jpg
/kaggle/input/letterboxd/posters/1653398.jpg
/kaggle/input/letterboxd/posters/1162167.jpg
/kaggle/input/letterboxd/posters/1457190.jpg
/kaggle/input/letterboxd/posters/1068446.jpg
/kaggle/input/letterboxd/posters/1482267.jpg
/kaggle/input/letterboxd/posters/1578276.jpg
/kaggle/input/letterboxd/posters/1688718.jpg
/kaggle/input/letterboxd/posters/1046984.jpg
/kaggle/input/letterboxd/posters/1469977.jpg
/kaggle/input/letterboxd/posters/1026818.jpg
/kaggle/input/letterboxd/posters/1540546.jpg
/kaggle/input/letterboxd/posters/1755781.jpg
/kaggle/input/letterboxd/posters/1488022.jpg
/kaggle/input/letterboxd/posters/1421773.jpg
/kaggle/input/letterboxd/posters/1252545.jpg
/kaggle/input/letterboxd/posters/1012067.jpg
/kaggle/input/letterboxd/posters/1497288.jpg
/kaggle/input/letterboxd/posters/1506510.jpg
/kaggle/input/letterboxd/posters/1

In [ ]:
!pip install timm
!pip install grad-cam
!pip install ftfy regex tqdm
!pip install git+https://github.com/openai/CLIP.git

  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-md7tbgks
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git /tmp/pip-req-build-md7tbgks
  Resolved https://github.com/openai/CLIP.git to commit a1d071733d7111c9c014f024669f959182114e33
  Preparing metadata (setup.py) ... done


In [ ]:
import pandas as pd
genres = pd.read_csv('/kaggle/input/letterboxd/genres.csv')
movies = pd.read_csv('/kaggle/input/letterboxd/movies.csv')

In [ ]:
output = genres.groupby('id').agg(list)
output['genre'] = output[output['genre'].apply(lambda x: len(x) == 1)]
output = output.dropna()
output['genre'] = output['genre'].apply(lambda x: x[0])

In [ ]:
output.head()

genre
id            
1000004  Drama
1000046  Drama
1000063  Drama
1000067  Drama
1000085  Drama

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit label encoder and transform 'genre' column
output['genre'] = label_encoder.fit_transform(output['genre'])

# Label mapping
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print(label_mapping)

{'Action': 0, 'Adventure': 1, 'Animation': 2, 'Comedy': 3, 'Crime': 4, 'Documentary': 5, 'Drama': 6, 'Family': 7, 'Fantasy': 8, 'History': 9, 'Horror': 10, 'Music': 11, 'Mystery': 12, 'Romance': 13, 'Science Fiction': 14, 'TV Movie': 15, 'Thriller': 16, 'War': 17, 'Western': 18}


Turn into a dataframe

In [ ]:
df = output.reset_index()
movie_info_df = pd.merge(movies, df, on='id')
movie_info_df.head()

id                             name    date  \
0  1000004                       Fight Club  1999.0   
1  1000046               The Social Network  2010.0   
2  1000063               Dead Poets Society  1989.0   
3  1000067  The Perks of Being a Wallflower  2012.0   
4  1000085                Good Will Hunting  1997.0   

                                             tagline  \
0                            Mischief. Mayhem. Soap.   
1  You don't get to 500 million friends without m...   
2  He was their inspiration. He made their lives ...   
3                                   We are infinite.   
4  Some people can never believe in themselves, u...   

                                         description  minute  rating  genre  
0  A ticking-time-bomb insomniac and a slippery s...   139.0    4.27      6  
1  On a fall night in 2003, Harvard undergrad and...   121.0    3.96      6  
2  At an elite, old-fashioned boarding school in ...   128.0    4.24      6  
3  Pittsburgh, Pennsylvania, 1991. High school fr...   103.0    3.90      6  
4  Will Hunting has a genius-level IQ but chooses...   127.0    4.29      6

In [ ]:
import os
from PIL import Image
import pandas as pd

# Assuming you have the DataFrame 'df' with the columns 'id', 'name', 'date', 'tagline', 'description', 'minute', 'rating', 'genre'
kaggle_path = '/kaggle/input/letterboxd/posters/'

# Initialize a list to store the indices of the rows to be dropped
rows_to_drop = []

# Check if the IDs in the DataFrame match the image files and have three channels
for idx, row in movie_info_df.iterrows():
    file_path = os.path.join(kaggle_path, f"{row['id']}.jpg")
    if os.path.exists(file_path):
        try:
            img = Image.open(file_path)
            if img.mode != 'RGB':
                print(f"Invalid image for ID {row['id']}: {row['name']}")
                rows_to_drop.append(idx)
        except:
            print(f"Error opening image for ID {row['id']}: {row['name']}")
            rows_to_drop.append(idx)
    else:
        print(f"Missing image for ID {row['id']}: {row['name']}")
        rows_to_drop.append(idx)

# Drop the rows with missing or invalid images
movie_info_df = movie_info_df.drop(movie_info_df.index[rows_to_drop])

# Reset the index of the DataFrame
movie_info_df = movie_info_df.reset_index(drop=True)

串流輸出內容已截斷至最後 5000 行。
Missing image for ID 1858613: Ana men Chile
Missing image for ID 1858619: Sporting Dreams
Missing image for ID 1858623: 101 East
Missing image for ID 1858639: Tarlan Kulakhmet Khodzhikov
Missing image for ID 1858642: Testing Lab
Missing image for ID 1858645: Cartwheels and Backflips
Missing image for ID 1858651: In Space - 50 Jahre Weltraumeroberung durch ESA und NASA
Missing image for ID 1858658: Orphan Hero
Missing image for ID 1858661: Mildred Scheel - Die First Lady und der Kampf gegen Krebs
Missing image for ID 1858672: Tajemství věstonických Venuší
Missing image for ID 1858681: A Conversation About Growing Up Black
Invalid image for ID 1858684: L'énigme du vol MH370
Missing image for ID 1858689: Harald Juhnke - Letztes großes Interview vor Erkrankung
Missing image for ID 1858704: Cem Aplausos
Missing image for ID 1858712: A Lament
Missing image for ID 1858714: Leemte
Missing image for ID 1858717: Papouasie, expédition au coeur d'un monde perdu
Missing image f

In [ ]:
movie_info_df.head()

id                             name    date  \
0  1000004                       Fight Club  1999.0   
1  1000046               The Social Network  2010.0   
2  1000063               Dead Poets Society  1989.0   
3  1000067  The Perks of Being a Wallflower  2012.0   
4  1000085                Good Will Hunting  1997.0   

                                             tagline  \
0                            Mischief. Mayhem. Soap.   
1  You don't get to 500 million friends without m...   
2  He was their inspiration. He made their lives ...   
3                                   We are infinite.   
4  Some people can never believe in themselves, u...   

                                         description  minute  rating  genre  
0  A ticking-time-bomb insomniac and a slippery s...   139.0    4.27      6  
1  On a fall night in 2003, Harvard undergrad and...   121.0    3.96      6  
2  At an elite, old-fashioned boarding school in ...   128.0    4.24      6  
3  Pittsburgh, Pennsylvania, 1991. High school fr...   103.0    3.90      6  
4  Will Hunting has a genius-level IQ but chooses...   127.0    4.29      6

In [ ]:
movie_info_df['genre'].value_counts()

genre
5     98733
6     85878
3     46421
2     22259
11    17995
10    17511
16     5613
0      5380
13     5000
18     4035
4      3111
7      2881
14     2642
8      1724
1      1616
12     1590
17      756
9       753
15      612
Name: count, dtype: int64

In [ ]:
movie_info_df = movie_info_df[movie_info_df['date'] >= 2000]

In [ ]:
movie_info_df.head()

id                             name    date  \
1  1000046               The Social Network  2010.0   
3  1000067  The Perks of Being a Wallflower  2012.0   
5  1000095                        Moonlight  2016.0   
6  1000097                       Mean Girls  2004.0   
7  1000110                         Aftersun  2022.0   

                                             tagline  \
1  You don't get to 500 million friends without m...   
3                                   We are infinite.   
5                    This is the story of a lifetime   
6                             Welcome to girl world.   
7                                      Memory burns.   

                                         description  minute  rating  genre  
1  On a fall night in 2003, Harvard undergrad and...   121.0    3.96      6  
3  Pittsburgh, Pennsylvania, 1991. High school fr...   103.0    3.90      6  
5  The tender, heartbreaking story of a young man...   111.0    4.20      6  
6  Cady Heron is a hit with The Plastics, the A-l...    97.0    3.82      3  
7  Sophie reflects on the shared joy and private ...   102.0    4.25      6

Create the MoviePosterDataset

In [ ]:
import os
from PIL import Image, UnidentifiedImageError
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

class MoviePosterDataset(Dataset):
    def __init__(self, root_dir, movie_info_df, transform = None):
        self.root_dir = root_dir
        self.movie_info_df = movie_info_df
        self.transform = transform

    def __len__(self):
        return len(self.movie_info_df)

    def __getitem__(self, idx):

        img_path = os.path.join(self.root_dir, str(self.movie_info_df.iloc[idx]['id']) + '.jpg')
        # if not os.path.exists(img_path):
        #   # If the image file doesn't exist, skip the iteration
        #   return None, None, None, None, None, None, None, None
        # print(img_path)
        image = Image.open(img_path)


        if self.transform:
            image = self.transform(image)

        genre = self.movie_info_df.iloc[idx]['genre']
        movie_id = self.movie_info_df.iloc[idx]['id']
        date = self.movie_info_df.iloc[idx]['date']
        minute = self.movie_info_df.iloc[idx]['minute']
        rating = self.movie_info_df.iloc[idx]['rating']
        name = str(self.movie_info_df.iloc[idx]['name'][0:30]) if not pd.isna(self.movie_info_df.iloc[idx]['name']) else ""
        description = str(self.movie_info_df.iloc[idx]['description']) if not pd.isna(self.movie_info_df.iloc[idx]['description']) else ""
        tagline = str(self.movie_info_df.iloc[idx]['tagline']) if not pd.isna(self.movie_info_df.iloc[idx]['tagline']) else ""
        # name = self.movie_info_df.iloc[idx]['name']
        # description = self.movie_info_df.iloc[idx]['description']
        # tagline = self.movie_info_df.iloc[idx]['tagline']
        return image, movie_id, date, minute, rating, name, description, tagline, genre


In [ ]:
import numpy as np
import timm.data.auto_augment as auto_augment

from sklearn.model_selection import train_test_split

# Assuming you have a DataFrame 'df' with the following columns:
# 'images', 'movie_ids', 'dates', 'ratings', 'languages', 'descriptions', 'taglines', 'labels'

data_transforms = transforms.Compose([
    # auto_augment.AutoAugment(policy = 'original'),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Split the data into training and validation sets
train_idx, val_idx = train_test_split(
    movie_info_df.index,
    test_size = 0.2,
    random_state = 42
)

# Create the training dataset
train_dataset = MoviePosterDataset(
    root_dir='/kaggle/input/letterboxd/posters',
    movie_info_df = movie_info_df,
    transform = data_transforms
)

# Create the validation dataset
val_dataset = MoviePosterDataset(
    root_dir='/kaggle/input/letterboxd/posters',
    movie_info_df = movie_info_df,
    transform= data_transforms
)

train_loader = DataLoader(train_dataset, batch_size= 1024, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size= 1024, shuffle=False, num_workers=4)

In [ ]:
movie_info_df.head()

id                             name    date  \
1  1000046               The Social Network  2010.0   
3  1000067  The Perks of Being a Wallflower  2012.0   
5  1000095                        Moonlight  2016.0   
6  1000097                       Mean Girls  2004.0   
7  1000110                         Aftersun  2022.0   

                                             tagline  \
1  You don't get to 500 million friends without m...   
3                                   We are infinite.   
5                    This is the story of a lifetime   
6                             Welcome to girl world.   
7                                      Memory burns.   

                                         description  minute  rating  genre  
1  On a fall night in 2003, Harvard undergrad and...   121.0    3.96      6  
3  Pittsburgh, Pennsylvania, 1991. High school fr...   103.0    3.90      6  
5  The tender, heartbreaking story of a young man...   111.0    4.20      6  
6  Cady Heron is a hit with The Plastics, the A-l...    97.0    3.82      3  
7  Sophie reflects on the shared joy and private ...   102.0    4.25      6

Clip Model - zero shots models


In [ ]:
import clip
clip.available_models()

['RN50',
 'RN101',
 'RN50x4',
 'RN50x16',
 'RN50x64',
 'ViT-B/32',
 'ViT-B/16',
 'ViT-L/14',
 'ViT-L/14@336px']

In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN50", device=device)

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Testing: 100%|██████████| 208/208 [08:20<00:00,  2.41s/batch]


AUC-ROC: 0.7562
F1-score: 0.1508
Precision: 0.1794
Accuracy: 0.2635


In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN101", device=device)

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

100%|███████████████████████████████████████| 278M/278M [00:19<00:00, 14.9MiB/s]
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Testing: 100%|██████████| 317/317 [17:34<00:00,  3.33s/batch]


AUC-ROC: 0.7823
F1-score: 0.1844
Precision: 0.2044
Accuracy: 0.2546


In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN50x4", device=device)

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

100%|████████████████████████████████████████| 338M/338M [00:02<00:00, 147MiB/s]
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Testing: 100%|██████████| 208/208 [04:37<00:00,  1.33s/batch]


AUC-ROC: 0.7979
F1-score: 0.1833
Precision: 0.1958
Accuracy: 0.3444


In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/16", device=device)

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

100%|███████████████████████████████████████| 335M/335M [00:04<00:00, 74.6MiB/s]
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Testing: 100%|██████████| 262/262 [18:23<00:00,  4.21s/batch]


AUC-ROC: 0.8116
F1-score: 0.2030
Precision: 0.2131
Accuracy: 0.3360


Fine Tuning the Clip Model

In [ ]:
# make the batch size of model smaller
import numpy as np
import timm.data.auto_augment as auto_augment

from sklearn.model_selection import train_test_split

# Assuming you have a DataFrame 'df' with the following columns:
# 'images', 'movie_ids', 'dates', 'ratings', 'languages', 'descriptions', 'taglines', 'labels'

data_transforms = transforms.Compose([
    # auto_augment.AutoAugment(policy = 'original'),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Split the data into training and validation sets
train_idx, val_idx = train_test_split(
    movie_info_df.index,
    test_size = 0.2,
    random_state = 42
)

# Create the training dataset
train_dataset = MoviePosterDataset(
    root_dir='/kaggle/input/letterboxd/posters',
    movie_info_df = movie_info_df,
    transform = data_transforms
)

# Create the validation dataset
val_dataset = MoviePosterDataset(
    root_dir='/kaggle/input/letterboxd/posters',
    movie_info_df = movie_info_df,
    transform= data_transforms
)

train_loader = DataLoader(train_dataset, batch_size= 256, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size= 256, shuffle=False, num_workers=4)

Fine Tune using movie name

In [ ]:
import clip
import torch.nn as nn
import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

# Set up the optimizer and loss function
optimizer = torch.optim.Adam(model.parameters(),lr=5e-5,betas=(0.9,0.98),eps=1e-6,weight_decay=0.2)
criterion = nn.CrossEntropyLoss()

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    train_loader_tqdm = tqdm.tqdm(iter(train_loader), desc=f'Epoch {epoch}', unit='batch')

    for images, movie_id, date, minute, rating, name, description, tagline, labels in train_loader_tqdm:
        optimizer.zero_grad()
        images = images.to(device)

        texts = clip.tokenize(name).to(device)

        # Forward pass
        logits_per_image, logits_per_text = model(images, texts)

        # Compute loss
        ground_truth = torch.arange(len(images),dtype=torch.long,device=device)
        total_loss = (criterion(logits_per_image, ground_truth) + criterion(logits_per_text, ground_truth))/2

        # Backward pass
        total_loss.backward()
        optimizer.step()

        # Update the progress bar
        train_loader_tqdm.set_postfix(loss=total_loss.item())

Epoch 4: 100%|██████████| 1268/1268 [16:37<00:00,  1.27batch/s, loss=5.06]


In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()
        print(probs)
        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

        # Pick the top 5 most similar labels for the image
        image_features /= image_features.norm(dim=-1, keepdim=True)
        text_features /= text_features.norm(dim=-1, keepdim=True)
        similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)
        print(similarity)
        values, indices = similarity[0].topk(5)
        print(values)

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Testing:   0%|          | 1/1268 [00:01<39:17,  1.86s/batch]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   0%|          | 2/1268 [00:02<19:57,  1.06batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   0%|          | 3/1268 [00:02<13:47,  1.53batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   0%|          | 4/1268 [00:02<10:56,  1.93batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   0%|          | 5/1268 [00:03<09:54,  2.13batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   0%|          | 6/1268 [00:03<08:43,  2.41batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 7/1268 [00:03<07:58,  2.64batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 8/1268 [00:04<07:30,  2.80batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 9/1268 [00:04<07:13,  2.90batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 10/1268 [00:04<07:00,  2.99batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 11/1268 [00:05<06:51,  3.05batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 12/1268 [00:05<06:45,  3.10batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 13/1268 [00:05<06:43,  3.11batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)


Testing:   1%|          | 14/1268 [00:06<09:01,  2.31batch/s]

[[0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 ...
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]
 [0.05264 0.05264 0.05264 ... 0.05264 0.05264 0.05264]]
tensor([[0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        ...,
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526],
        [0.0526, 0.0526, 0.0526,  ..., 0.0526, 0.0526, 0.0526]],
       device='cuda:0', dtype=torch.float16)
tensor([0.0526, 0.0526, 0.0526, 0.0526, 0.0526], device='cuda:0',
       dtype=torch.float16)



Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x790cb77270a0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt: 


KeyboardInterrupt: 

Fine Tune with Genre name

In [ ]:
import clip
import torch.nn as nn
import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

# Label mapping
label_mapping = dict(zip(label_encoder.transform(label_encoder.classes_), label_encoder.classes_))
genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]

# Set up the optimizer and loss function
optimizer = torch.optim.Adam(model.parameters(),lr=5e-5,betas=(0.9,0.98),eps=1e-6,weight_decay=0.2)
criterion = nn.CrossEntropyLoss()

# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    train_loader_tqdm = tqdm.tqdm(iter(train_loader), desc=f'Epoch {epoch}', unit='batch')

    for images, movie_id, date, minute, rating, name, description, tagline, labels in train_loader_tqdm:
        optimizer.zero_grad()
        images = images.to(device)
        text = [f"A movie poster of {label_mapping[int(label)]} genre" for label in labels]
        texts = clip.tokenize(text).to(device)

        # Forward pass
        logits_per_image, logits_per_text = model(images, texts)

        # Compute loss
        ground_truth = torch.arange(len(images),dtype=torch.long,device=device)
        total_loss = (criterion(logits_per_image, ground_truth) + criterion(logits_per_text, ground_truth))/2

        # Backward pass
        total_loss.backward()
        optimizer.step()

        # Update the progress bar
        train_loader_tqdm.set_postfix(loss=total_loss.item())

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
Epoch 0: 100%|██████████| 1268/1268 [16:48<00:00,  1.26batch/s, loss=5.03]


In [ ]:
import torch
import clip
import tqdm
from PIL import Image
from sklearn.metrics import roc_auc_score, f1_score, precision_score, accuracy_score
import torch.nn.functional as F
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

genres = ['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']
genres = [f"A movie poster of {genre} genre" for genre in genres]
text = clip.tokenize(genres).to(device)

all_outputs = []
all_labels = []

with torch.no_grad():
    for images, movie_id, date, minute, rating, name, description, tagline, labels in tqdm.tqdm(iter(val_loader), desc='Testing', unit='batch'):
        images = images.to(device)
        labels = labels.to(device)

        image_features = model.encode_image(images)
        text_features = model.encode_text(text)

        logits_per_image, logits_per_text = model(images, text)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()

        all_outputs.extend(probs)
        all_labels.extend(labels.cpu().numpy())

        # # Pick the top 5 most similar labels for the image
        # image_features /= image_features.norm(dim=-1, keepdim=True)
        # text_features /= text_features.norm(dim=-1, keepdim=True)
        # similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)
        # print(similarity)
        # values, indices = similarity[0].topk(5)
        # print(values)

# Calculate the metrics
auc_roc = roc_auc_score(F.one_hot(torch.tensor(all_labels), num_classes=len(genres)).float(), all_outputs)
f1 = f1_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
precision = precision_score(all_labels, np.argmax(all_outputs, axis=1), average='macro')
accuracy = accuracy_score(all_labels, np.argmax(all_outputs, axis=1))

print(f'AUC-ROC: {auc_roc:.4f}')
print(f'F1-score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Accuracy: {accuracy:.4f}')

Testing: 100%|██████████| 1268/1268 [06:41<00:00,  3.16batch/s]


AUC-ROC: 0.6206
F1-score: 0.0382
Precision: 0.0739
Accuracy: 0.0920


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import torch
import gc

# Clear the GPU cache
torch.cuda.empty_cache()

# Explicitly delete tensors and models
del model
del preprocess
del images
del labels
torch.cuda.empty_cache()

# Collect garbage
gc.collect()

# Check the current GPU memory usage
print(f"GPU memory used: {torch.cuda.memory_allocated()/1024**2:.2f} MB")
print(f"GPU memory cached: {torch.cuda.memory_cached()/1024**2:.2f} MB")

import torch
torch.cuda.empty_cache()

NameError: name 'model' is not defined

In [ ]:
# Check the current GPU memory usage
print(f"GPU memory used: {torch.cuda.memory_allocated()/1024**2:.2f} MB")
print(f"GPU memory cached: {torch.cuda.memory_cached()/1024**2:.2f} MB")

GPU memory used: 22000.61 MB
GPU memory cached: 22226.00 MB


/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py:440: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
